//1. Import area
//1.1 Import DefaultImport from 'some library/location';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import A from '../Components/A'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <A name="arjun" msg="A11arjunyad"></A>
      
    </div>
  )
}
